/** Generated by YAKINDU Statechart Tools code generator. */
#include <string>
#include "gtest/gtest.h"
#include "Statechart.h"
#include "sc_runner_timed.h"
#include "sc_types.h"

#define SC_UNUSED(P) (void)P

namespace  {

Statechart* statechart;



//! The timers are managed by a timer service. */
static TimedSctUnitRunner * runner;

class StatechartTest : public ::testing::Test{
	protected:
	virtual void SetUp() {
		statechart = new Statechart();
		runner = new TimedSctUnitRunner(
			statechart,
			true,
			200
		);
		statechart->setTimerService(runner);
	}
	virtual void TearDown() {
		delete statechart;
		delete runner;
	}
};


TEST_F(StatechartTest, test_0to20) {
	
	statechart->enter();
	
	statechart->ultrasonic
	()->raise_0to20();
	
	EXPECT_TRUE(statechart->light
	()->isRaisedOFF());
	
	runner->proceed_time(1*1000);
	
	
}
TEST_F(StatechartTest, _20to30) {
	
	statechart->enter();
	
	statechart->ultrasonic
	()->raise_20to30();
	
	EXPECT_TRUE(statechart->light
	()->isRaisedONOFF());
	
	runner->proceed_time(1*1000);
	
	
}
TEST_F(StatechartTest, _30toLarger) {
	
	statechart->enter();
	
	statechart->ultrasonic
	()->raise_30toLarger();
	
	EXPECT_TRUE(statechart->light
	()->isRaisedON());
	
	runner->proceed_time(1*1000);
	
	
}

}

