/** Generated by YAKINDU Statechart Tools code generator. */
// #include <string>

#include "../statechart/Statechart.cpp"
// #include "../lib/googletest/googletest/include/gtest/gtest.h"
// #include <../lib/googletest/googletest/include/gtest>

// #define SC_UNUSED(P) (void)P
// #include "../googletest/googletest/include/gtest/gtest.h"
#include <AUnit.h>
using namespace aunit;
Statechart *statechart;

namespace
{

  // Statechart::Luz *luz();
  // Statechart::Pir *pir();

  //! The timers are managed by a timer service. */
  // static SctUnitRunner *runner;

  class StatechartTest : public TestOnce
  {
  protected:
    void setup() override
    {
      TestOnce::setup();

      statechart = new Statechart();
      // runner = new SctUnitRunner(
      //     statechart,
      //     true,
      //     200);
    }
    void teardown() override
    {

      delete statechart;
      TestOnce::teardown();

      // delete runner;
    }

  public:
    void setupTeste()
    {
      Serial.begin(115200);
      while (!Serial)
        ; // Wait until Serial is ready - Leonardo/Micro

      TestRunner::exclude("*");
      // TestRunner::include("looping*");
      TestRunner::include("StatechartTest", "*");
    }

    void loopTeste()
    {
      TestRunner::run();
    }
  };

  test(StatechartTest, testscases)
  {
    statechart->enter();
    assertTrue(statechart->luz->isRaisedOFF());
  }
  test(StatechartTest, testSinalPIR_SinalLuz)
  {

    statechart->enter();
    statechart->pir->raiseON();
    assertTrue(statechart->luz->isRaisedON());
    statechart->pir->raiseOFF();
    assertTrue(statechart->luz->isRaisedOFF());
  }
  // test(StatechartTest, test5Ativacoes)
  // {

  //   statechart->enter();

  //   // sc_integer i = 0;
  //   int i = 0;

  //   statechart->pir()->raiseON();

  //   i = i + 1;

  //   while ((i) < (5))
  //   {
  //     i = i + 1;
  //     statechart->pir()->raiseOFF();
  //     statechart->pir()->raiseON();
  //   }

  //   statechart->pir()->raiseON();

  //   assertTrue((statechart->getCount()) == (5));

  //   // EXPECT_TRUE(statechart->isStateActive(Statechart::main_region_Estado5Ativacoes));

  //   // statechart->pir()->raiseON();

  //   // EXPECT_TRUE(statechart->isStateActive(Statechart::main_region__final_));
  // }

}
